// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfstzsuuvdkgfvkpjwqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmc3R6c3V1dmRrZ2Z2a3Bqd3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTQ2NzksImV4cCI6MjA3MDU3MDY3OX0.j59eOO5hN-JIb0yCp7vAGcuaYPpBF4Z6KlTLJjpaUkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});